[workspace]
resolver = "3"
members = [
    "crates/common",
    "crates/vehicle_device_bus",
    "crates/gateway",
    "crates/emulator",
    "crates/remotive_bridge",
    "crates/front_headlamp_actuator",
    "crates/wiper_actuator",
    "crates/tui_dashboard", # Add this here
    "crates/observation",
]
